name: Testing

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - shell: bash
      env:
          API_KEY: ${{ secrets.API_KEY }}
      run: |
        echo "$API_KEY" >> api_key.txt
    - name: Gradle Test Action
      uses: gradle/gradle-build-action@v2.0.1
      with:
        arguments: test
