name: Testing

on:
  workflow_dispatch:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Create secret token for tests
      shell: bash
      env:
          API_KEY: ${{ secrets.API_KEY }}
      run: |
        echo "$API_KEY" >> api_key.txt
    - name: Grant Permissions to gradlew
      run: chmod +x gradlew
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1.0.4
    - name: Gradle Test Action
      run: ./gradlew test
